run-name: Python code analysis for ${{ inputs.branch }}
name: Python code analysis

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to scan"
        required: true
        default: ""
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
        default: ""

jobs:
  bandit:
    name: Python static code analysis for ${{ inputs.branch }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkot the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Bandit Scan
        uses: shundor/python-bandit-scan@v1.0
        with:
          exit_zero: true
          excluded_paths: .git,__pycache__,*/test_*,*/test/*,*/tests/*,*/testing/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
