name: Build GCC Packages

on:
  workflow_dispatch:
    inputs:
      gcc_url:
        description: "GCC source tarball URL"
        required: true
        default: "https://ftp.gnu.org/gnu/gcc/gcc-15.1.0/gcc-15.1.0.tar.xz"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    container:
      image: debian:8
    steps:
      - name: Configure repository
        run: |
          rm -f /etc/apt/sources.list && \
          printf 'deb [check-valid-until=no] http://archive.debian.org/debian jessie main contrib non-free\n' \
          > /etc/apt/sources.list && \
          printf 'deb [check-valid-until=no] http://archive.debian.org/debian-security jessie/updates main contrib non-free\n' \
          >> /etc/apt/sources.list && \
          echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/90no-check-valid
      - name: Install dependencies
        run: |
            apt-get -o Acquire::AllowInsecureRepositories=true \
            -o Acquire::Check-Valid-Until=false update && \
            DEBIAN_FRONTEND=noninteractive \
            apt-get install -y --allow-unauthenticated --no-install-recommends \
            build-essential curl ca-certificates \
            bzip2 xz-utils git make flex texinfo \
            libgmp-dev libmpfr-dev libmpc-dev zlib1g-dev \
            ruby ruby-dev wget && \
            apt-get clean && rm -rf /var/lib/apt/lists/*

      - name: Build GCC 8.5 Stage 1
        run: |
          curl -LO https://ftp.gnu.org/gnu/gcc/gcc-8.5.0/gcc-8.5.0.tar.xz && \
          tar -xf gcc-8.5.0.tar.xz && \
          cd gcc-8.5.0 && \
          ./contrib/download_prerequisites && \
          mkdir -p build && cd build && \
          ../configure --prefix=/opt/gcc-8.5.0 \
                       --disable-multilib \
                       --enable-languages=c,c++ \
                       --with-system-zlib \
                       --disable-bootstrap && \
          make && make install-strip
      - name: Build and package GCC .deb
        run: |
          mkdir -p /packages
          cd /usr/src
          wget "${{ github.event.inputs.gcc_url }}" -O gcc.tar.xz
          tar -xf gcc.tar.xz
          cd gcc-*
          PATH=/opt/gcc-8.5.0/bin:$PATH \
          CC=/opt/gcc-8.5.0/bin/gcc \
          CXX=/opt/gcc-8.5.0/bin/g++
          ./contrib/download_prerequisites
          mkdir build && cd build
          ../configure --prefix=/opt/gcc-15 --disable-multilib --enable-languages=c,c++ --with-system-zlib
          make -j$(nproc)
          make install-strip

          mkdir -p /pkgbuild/gcc15/DEBIAN
          cat <<EOF > /pkgbuild/gcc15/DEBIAN/control
          Package: gcc15
          Version: 15.1-1
          Section: devel
          Priority: optional
          Architecture: amd64
          Maintainer: bootstrap <root@localhost>
          Provides: gcc, g++
          Description: GNU Compiler Collection 15.1
          EOF

          mkdir -p /pkgbuild/gcc15/opt
          cp -a /opt/gcc-15 /pkgbuild/gcc15/opt/
          chmod 755 /pkgbuild/gcc15/DEBIAN
          dpkg-deb --build /pkgbuild/gcc15 /packages

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcc-deb
          path: /packages/*.deb

  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: Configure repository
        run: |
          sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*.repo && \
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo
      - name: Install deps and setup
        run: |
          yum -y install centos-release-scl-rh epel-release
          sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-SCLo-*.repo
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g' /etc/yum.repos.d/CentOS-SCLo-*.repo
          yum -y install devtoolset-11-gcc devtoolset-11-gcc-c++ \
            git make bzip2 xz wget \
            gmp-devel mpfr-devel libmpc-devel isl-devel zlib-devel \
            texinfo flex diffutils rpm-build
          yum clean all

      - name: Build and package GCC .rpm
        run: |
          source /opt/rh/devtoolset-11/enable
          mkdir -p /packages
          cd /usr/src
          wget "${{ github.event.inputs.gcc_url }}" -O gcc.tar.xz
          tar -xf gcc.tar.xz
          cd gcc-*
          ./contrib/download_prerequisites
          mkdir build && cd build
          ../configure --prefix=/opt/gcc-15 --disable-multilib --enable-languages=c,c++ --with-system-zlib
          make -j$(nproc)
          make install-strip

          mkdir -p /tmp/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          mkdir -p /tmp/rpmbuild/SOURCES/gcc15/opt
          cp -a /opt/gcc-15 /tmp/rpmbuild/SOURCES/gcc15/opt/
          tar -czf /tmp/rpmbuild/SOURCES/gcc15.tar.gz -C /tmp/rpmbuild/SOURCES gcc15
          rm -rf /tmp/rpmbuild/SOURCES/gcc15
          cat <<EOF > /tmp/rpmbuild/SPECS/gcc15.spec
          Name: gcc15
          Version: 15.1
          Release: 1
          Summary: GCC 15.1 built manually
          License: GPLv3+
          Group: Development/Tools
          BuildArch: x86_64
          AutoReqProv: no
          Source0: gcc15.tar.gz

          %description
          GCC 15.1 built manually and installed to /opt/gcc-15.

          %prep
          %setup -q -c -a 0

          %install
          mkdir -p %{buildroot}/opt
          cp -a gcc15/opt/gcc-15 %{buildroot}/opt/

          %files
          /opt/gcc-15
          EOF
          rpmbuild -bb --define "_topdir /tmp/rpmbuild" /tmp/rpmbuild/SPECS/gcc15.spec
          cp /tmp/rpmbuild/RPMS/x86_64/*.rpm /packages

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcc-rpm
          path: /packages/*.rpm
